### ISSUE TITLE
Errors are wrapped

### ISSUE THREAD

**Issue by shyim** [chientrm/wrangler-proxy#15]
When I want to try catch errors I get errors like:

```
‌{"status":500,"statusText":"Internal Server Error","message":"{\"name\":\"Error\",\"message\":\"D1_ERROR: UNIQUE constraint failed: user.username\",\"stack\":\"Error: D1_ERROR: UNIQUE constraint failed: user.username\\n    at D1Database._sendOrThrow (cloudflare-internal:d1-api:66:19)\\n    at async D1Database.batch (cloudflare-internal:d1-api:35:22)\\n    at async o6.execute (file:///Users/shyim/Downloads/shopmon/.wrangler/tmp/dev-koxavv/worker.js:170:132)\\n    at async Object.fetch (file:///Users/shyim/Downloads/shopmon/.wrangler/tmp/dev-koxavv/worker.js:449:29)\\n    at async jsonError (file:///Users/shyim/Downloads/shopmon/.wrangler/tmp/dev-koxavv/worker.js:469:12)\"}"}
```

The real error is inside the message as JSON. Therefore such checks in libraries are not working:
https://github.com/lucia-auth/lucia/blob/main/packages/adapter-sqlite/src/drivers/d1.ts#L58-L64

**Comment by chientrm** [comment]
> When I want to try catch errors I get errors like:
> 
> ```
> ‌{"status":500,"statusText":"Internal Server Error","message":"{\"name\":\"Error\",\"message\":\"D1_ERROR: UNIQUE constraint failed: user.username\",\"stack\":\"Error: D1_ERROR: UNIQUE constraint failed: user.username\\n    at D1Database._sendOrThrow (cloudflare-internal:d1-api:66:19)\\n    at async D1Database.batch (cloudflare-internal:d1-api:35:22)\\n    at async o6.execute (file:///Users/shyim/Downloads/shopmon/.wrangler/tmp/dev-koxavv/worker.js:170:132)\\n    at async Object.fetch (file:///Users/shyim/Downloads/shopmon/.wrangler/tmp/dev-koxavv/worker.js:449:29)\\n    at async jsonError (file:///Users/shyim/Downloads/shopmon/.wrangler/tmp/dev-koxavv/worker.js:469:12)\"}"}
> ```
> 
> The real error is inside the message as JSON. Therefore such checks in libraries are not working: https://github.com/lucia-auth/lucia/blob/main/packages/adapter-sqlite/src/drivers/d1.ts#L58-L64

Should've been fixed by https://github.com/chientrm/wrangler-proxy/releases/tag/2.2.3
