### ISSUE TITLE
R2 `PUT` operation not working

### ISSUE THREAD

**Issue by bruceharrison1984** [chientrm/wrangler-proxy#17]
I've got the setup with a small Svelte project, and any attempt to use a PUT operation with R2 fails.

```ts
const r2 = event.platform?.env.TORCH_R2 ?? connectR2('R2_STORE');
if (!r2) throw new Error('Torch R2 binding not found');

await r2.put('newvalue', 'test'); <-- stack points here
```

Wrangler-proxy Console Error:
```sh
[wrangler:inf] POST /instruction 200 OK (2ms)
[wrangler:inf] POST /data 500 Internal Server Error (3ms)   
```

Svelte Console Error
```sh
Error: {"name":"TypeError","message":"Provided readable stream must have a known length (request/response body or readable half of FixedLengthStream)","stack":"TypeError: Provided readable stream must have a known length (request/response body or readable half of FixedLengthStream)"}
    at W (file:///C:/Users/XXX/development/svelte-test/node_modules/wrangler-proxy/dist/index.js:1:197)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async o.post (file:///C:/Users/XXX/development/svelte-test/node_modules/wrangler-proxy/dist/index.js:1:714)
    at async Module.init (C:\Users\XXX\development\svelte-test\src\lib\middleware\init.ts:29:3)
    at async Object.handle (C:\Users\XXX\development\svelte-test\src\hooks.server.ts:9:14)
    at async Module.respond (C:\Users\XXX\development\svelte-test\node_modules\@sveltejs\kit\src\runtime\server\respond.js:282:20)
    at async file:///C:/Users/XXX/development/svelte-test/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:502:22
j {
  host: 'http://127.0.0.1:8787',
  name: 'R2_STORE',
  metadata: {},
  data: null <-- null?
}
```

It looks like `data` is null, but I am passing a value.

**Comment by chientrm** [comment]
> I've got the setup with a small Svelte project, and any attempt to use a PUT operation with R2 fails.
> 
> ```ts
> const r2 = event.platform?.env.TORCH_R2 ?? connectR2('R2_STORE');
> if (!r2) throw new Error('Torch R2 binding not found');
> 
> await r2.put('newvalue', 'test'); <-- stack points here
> ```
> 
> Wrangler-proxy Console Error:
> 
> ```shell
> [wrangler:inf] POST /instruction 200 OK (2ms)
> [wrangler:inf] POST /data 500 Internal Server Error (3ms)   
> ```
> 
> Svelte Console Error
> 
> ```shell
> Error: {"name":"TypeError","message":"Provided readable stream must have a known length (request/response body or readable half of FixedLengthStream)","stack":"TypeError: Provided readable stream must have a known length (request/response body or readable half of FixedLengthStream)"}
>     at W (file:///C:/Users/XXX/development/svelte-test/node_modules/wrangler-proxy/dist/index.js:1:197)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async o.post (file:///C:/Users/XXX/development/svelte-test/node_modules/wrangler-proxy/dist/index.js:1:714)
>     at async Module.init (C:\Users\XXX\development\svelte-test\src\lib\middleware\init.ts:29:3)
>     at async Object.handle (C:\Users\XXX\development\svelte-test\src\hooks.server.ts:9:14)
>     at async Module.respond (C:\Users\XXX\development\svelte-test\node_modules\@sveltejs\kit\src\runtime\server\respond.js:282:20)
>     at async file:///C:/Users/XXX/development/svelte-test/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:502:22
> j {
>   host: 'http://127.0.0.1:8787',
>   name: 'R2_STORE',
>   metadata: {},
>   data: null <-- null?
> }
> ```
> 
> It looks like `data` is null, but I am passing a value.

I made a small reproduce here: https://github.com/chientrm/wrangler-proxy-r2-bug

It seem to `put` correctly.

Please try update `wrangler-proxy` version to the latest and restart the proxy process.

**Comment by bruceharrison1984** [comment]
I appreciate your example. 

The difference appears to be R2 doesn't work *locally*. If I add the `--remote` flag to when running wrangler-proxy, it does indeed work correctly. If I remove it, then the above error occurs again. 

I presumed this library supports local workflows as well, or am I incorrect in that assumption? D1 seems to work perfectly locally.

**Comment by chientrm** [comment]
> I appreciate your example.
> 
> The difference appears to be R2 doesn't work _locally_. If I add the `--remote` flag to when running wrangler-proxy, it does indeed work correctly. If I remove it, then the above error occurs again.
> 
> I presumed this library supports local workflows as well, or am I incorrect in that assumption? D1 seems to work perfectly locally.

I have no idea lol.
`wrangler-proxy` was originally designed to work with remote mode. When I first started, local mode was not available.

**Comment by bruceharrison1984** [comment]
Ah, ok then! That would totally explain my issue then lol
