### ISSUE TITLE
Trying to get fetch() working with image re-size

### ISSUE THREAD

**Issue by saturnonearth** [chientrm/wrangler-proxy#20]
Goal is to re-size image and then upload to R2 - so the idea was to use the service binding `fetch()` to re-size an image so I can then upload it to R2 - but I wasn't exactly sure if it was implemented.

I see that `fetch()` is proxied, but I am getting `Error: Method not implemented.` when trying to call the fetch request with `cf-image` options.

Perhaps I am doing this incorrectly? Is there an example of this possibly?

**Comment by chientrm** [comment]
> Goal is to re-size image and then upload to R2 - so the idea was to use the service binding `fetch()` to re-size an image so I can then upload it to R2 - but I wasn't exactly sure if it was implemented.
> 
> I see that `fetch()` is proxied, but I am getting `Error: Method not implemented.` when trying to call the fetch request with `cf-image` options.
> 
> Perhaps I am doing this incorrectly? Is there an example of this possibly?

Updated docs at [Service Bindings](https://github.com/chientrm/wrangler-proxy#service-bindings)

**Comment by saturnonearth** [comment]
Thanks for the update - unfortunately I am still unable to make this work. It is still giving me the "Method not implemented.". Is it because I have no service binding setup in wrangler.toml? I am trying to call fetch to re-size an image. ([as seen here](https://developers.cloudflare.com/images/transform-images/transform-via-workers/))

Is this scenario possible with this library?

**Comment by chientrm** [comment]
> Thanks for the update - unfortunately I am still unable to make this work. It is still giving me the "Method not implemented.". Is it because I have no service binding setup in wrangler.toml? I am trying to call fetch to re-size an image. ([as seen here](https://developers.cloudflare.com/images/transform-images/transform-via-workers/))
> 
> Is this scenario possible with this library?
Did you upgrade to the latest version?

**Comment by saturnonearth** [comment]
Yes I am using the latest version

**Comment by chientrm** [comment]
> Yes I am using the latest version

Did you bind it in your wrangler.toml or CF dashboard?

**Comment by saturnonearth** [comment]
> > Yes I am using the latest version
> 
> Did you bind it in your wrangler.toml or CF dashboard?

I am not sure what to bind because `fetch()` is used within the worker itself - so I am not sure how to bind a worker to itself?

**Comment by chientrm** [comment]
> > > Yes I am using the latest version
> > 
> > 
> > Did you bind it in your wrangler.toml or CF dashboard?
> 
> I am not sure what to bind because `fetch()` is used within the worker itself - so I am not sure how to bind a worker to itself?

Can I see your full `fetch()` invoke?

**Comment by saturnonearth** [comment]
> Can I see your full `fetch()` invoke?

```ts
	await locals.SB.fetch(imageURL, {
		body: JSON.stringify({
			cf: {
				image: {
					width: 100
				}
			}
		})
	});
```

**Comment by chientrm** [comment]
> > Can I see your full `fetch()` invoke?
> 
> ```ts
> 	await locals.SB.fetch(imageURL, {
> 		body: JSON.stringify({
> 			cf: {
> 				image: {
> 					width: 100
> 				}
> 			}
> 		})
> 	});
> ```

You can try [2.2.7](https://github.com/chientrm/wrangler-proxy/releases/tag/2.2.7)

It's not fixed yet but it will show more error details 👍

**Comment by saturnonearth** [comment]
> It's not fixed yet but it will show more error details 👍

Thanks!

Ah I see. The proxy needs a binding to work, which I now added that connected to a worker that re-sizes images, but I was hoping to be able to re-size from within the sveltekit function endpoint itself, and not need to bind to a separate worker. Not sure if that is possible or not.

**Comment by chientrm** [comment]
> > It's not fixed yet but it will show more error details 👍
> 
> Thanks!
> 
> Ah I see. The proxy needs a binding to work, which I now added that connected to a worker that re-sizes images, but I was hoping to be able to re-size from within the sveltekit function endpoint itself, and not need to bind to a separate worker. Not sure if that is possible or not.

Then you can use a normal `fetch` directly to that worker API endpoint 🤔

**Comment by saturnonearth** [comment]
Ah yea I figured I can just fetch via the URL method of image transforms - thanks!
