### ISSUE TITLE
About the future of `wrangler-proxy` since `wrangler@3.24.0` and up exposes `getBindingsProxy`

### ISSUE THREAD

**Issue by Jolg42** [chientrm/wrangler-proxy#23]
Hello!

Since https://github.com/cloudflare/workers-sdk/releases/tag/wrangler%403.24.0 it is now possible to do the following:

```ts
import { getBindingsProxy } from "wrangler";

const { bindings, dispose } = await getBindingsProxy();

try {
	const myKv = bindings.MY_KV;
	const kvValue = await myKv.get("my-kv-key");

	console.log(`KV Value = ${kvValue}`);
} finally {
	await dispose();
}
```

The PR is https://github.com/cloudflare/workers-sdk/pull/4523

@chientrm Maybe you already know about this, I wanted to mention it, in my context I first used `wrangler-proxy`, to query D1, which worked great! And now switched to `getBindingsProxy` and it also works great! I like how it's an official feature now 🙌🏼 

So, I'm not sure what it means for this project here, if you see the need to continue or to recommend `getBindingsProxy` instead? Just curious about your thoughts.

**Comment by chientrm** [comment]
> Hello!
> 
> Since https://github.com/cloudflare/workers-sdk/releases/tag/wrangler%403.24.0 it is now possible to do the following:
> 
> ```ts
> import { getBindingsProxy } from "wrangler";
> 
> const { bindings, dispose } = await getBindingsProxy();
> 
> try {
> 	const myKv = bindings.MY_KV;
> 	const kvValue = await myKv.get("my-kv-key");
> 
> 	console.log(`KV Value = ${kvValue}`);
> } finally {
> 	await dispose();
> }
> ```
> 
> The PR is [cloudflare/workers-sdk#4523](https://github.com/cloudflare/workers-sdk/pull/4523)
> 
> @chientrm Maybe you already know about this, I wanted to mention it, in my context I first used `wrangler-proxy`, to query D1, which worked great! And now switched to `getBindingsProxy` and it also works great! I like how it's an official feature now 🙌🏼
> 
> So, I'm not sure what it means for this project here, if you see the need to continue or to recommend `getBindingsProxy` instead? Just curious about your thoughts.

Ohm, maybe I'll add some `auth` layers and make `wrangler-proxy` a way for people to expose and access Workers resources over the internet 🤔 .
I'll still use `wrangler-proxy` for a while until `getBindingsProxy` is stable proof 👍

**Comment by nicolas-albert** [comment]
I recently attempted this approach.
While it successfully connects my local D1 instance with a miniflare, I haven't been able to determine if it can establish a connection with my remote/production D1.
This functionality is crucial for me to query D1 during my application's build process.
For the time being, I'm utilizing the following command: `wrangler dev node_modules/wrangler-proxy/dist/worker.js --remote`.

**Comment by chientrm** [comment]
> I recently attempted this approach.
> While it successfully connects my local D1 instance with a miniflare, I haven't been able to determine if it can establish a connection with my remote/production D1.
> This functionality is crucial for me to query D1 during my application's build process.
> For the time being, I'm utilizing the following command: `wrangler dev node_modules/wrangler-proxy/dist/worker.js --remote`.

Yep I started building `wrangler-proxy` when `--local` mode was just experimenting.

**Comment by Jolg42** [comment]
Oh I see! I'm only using it locally for tests on my side. This is interesting.
