### ISSUE TITLE
Error in hook action

### ISSUE THREAD

**Issue by ethan-tqa** [chientrm/wrangler-proxy#3]
The example code
`waitUntil(async () => {}, platform?.context);`

has an error
`Argument of type '() => Promise<void>' is not assignable to parameter of type 'Promise<any>'.ts(2345)`

Perhaps it should be like this?
`waitUntil((async () => {})(), platform?.context);`

**Comment by chientrm** [comment]
> The example code `waitUntil(async () => {}, platform?.context);`
> 
> has an error `Argument of type '() => Promise<void>' is not assignable to parameter of type 'Promise<any>'.ts(2345)`
> 
> Perhaps it should be like this? `waitUntil((async () => {})(), platform?.context);`

Fixed by [2.1.4](https://github.com/chientrm/wrangler-proxy/releases/tag/2.1.4)
