### ISSUE TITLE
D1 Query Bugs

### ISSUE THREAD

**Issue by rac146** [chientrm/wrangler-proxy#9]
OK not sure if this is a problem with the proxy, but when attempting to use DrizzleORM and do a findFirst() query I'm getting the following error:

<img width="1072" alt="image" src="https://github.com/chientrm/wrangler-proxy/assets/6462376/25653a63-6ed0-420b-b2e4-6dfee7946a7d">

The same table running a query with findMany() works fine.. Also getting similar errors on any queries that involve where clauses.. Is there some query translation problem?

**Comment by rac146** [comment]
I can confirm this is the proxy - did a test deploy of findFirst and where clause queries into Cloudflare with no issues..

**Comment by BahaaZidan** [comment]
Same issue with me

**Comment by plainsquirrel** [comment]
Same problem  @chientrm  There is an issue when using where. What would be the best action to take to solve it?

**Comment by chientrm** [comment]
> Same problem @chientrm There is an issue when using where. What would be the best action to take to solve it?

I'm working on this. 👍

**Comment by chientrm** [comment]
It is fixed in latest version [2.2.2](https://github.com/chientrm/wrangler-proxy/releases/tag/2.2.2)
